package com.ucredit.service.web.idcard.request;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T17:16:59.025+08:00
 * Generated source version: 2.7.7
 */
@WebService(
        targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn",
        name = "QueryValidatorServices")
@XmlSeeAlso({ ObjectFactory.class })
public interface QueryValidatorServices {

    @WebResult(
            name = "querySingleReturn",
            targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
    @RequestWrapper(
            localName = "querySingle",
            targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn",
            className = "com.renrendai.service.web.QuerySingle")
    @WebMethod
    @ResponseWrapper(
            localName = "querySingleResponse",
            targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn",
            className = "com.renrendai.service.web.QuerySingleResponse")
    String querySingle(
            @WebParam(
                    name = "userName_",
                    targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") java.lang.String userName,
            @WebParam(
                    name = "password_",
                    targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") java.lang.String password,
            @WebParam(
                    name = "type_",
                    targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") java.lang.String type,
            @WebParam(
                    name = "param_",
                    targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") java.lang.String param);

    @WebResult(
            name = "queryBatchReturn",
            targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
    @RequestWrapper(
            localName = "queryBatch",
            targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn",
            className = "com.renrendai.service.web.QueryBatch")
    @WebMethod
    @ResponseWrapper(
            localName = "queryBatchResponse",
            targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn",
            className = "com.renrendai.service.web.QueryBatchResponse")
    String queryBatch(
            @WebParam(
                    name = "userName_",
                    targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") java.lang.String userName,
            @WebParam(
                    name = "password_",
                    targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") java.lang.String password,
            @WebParam(
                    name = "type_",
                    targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") java.lang.String type,
            @WebParam(
                    name = "param_",
                    targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") java.lang.String param);
}
