package com.ucredit.service.web.idcard.request;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T17:16:59.012+08:00
 * Generated source version: 2.7.7
 */

@javax.jws.WebService(
        serviceName = "QueryValidatorServicesService",
        portName = "QueryValidatorServices",
        targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn",
        wsdlLocation = "http://gboss.id5.cn/services/QueryValidatorServices?wsdl",
        endpointInterface = "com.renrendai.service.web.QueryValidatorServices")
public class QueryValidatorServicesImpl implements QueryValidatorServices {
    @Override
    public java.lang.String querySingle(java.lang.String userName,
            java.lang.String password, java.lang.String type,
            java.lang.String param) {
        return null;
    }

    @Override
    public java.lang.String queryBatch(java.lang.String userName,
            java.lang.String password, java.lang.String type,
            java.lang.String param) {
        return null;
    }

}
