package com.ucredit.service.web.idcard.request;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T17:16:59.032+08:00
 * Generated source version: 2.7.7
 */

public class QueryValidatorServices_QueryValidatorServices_Server {

    protected QueryValidatorServices_QueryValidatorServices_Server() {
//        System.out.println("Starting Server");
        Object implementor = new QueryValidatorServicesImpl();
        String address = "http://app.service.validator.businesses.gboss.id5.cn/services/QueryValidatorServices";
        Endpoint.publish(address, implementor);
    }

//    public static void main(String args[]) throws java.lang.Exception {
//        new QueryValidatorServices_QueryValidatorServices_Server();
//        System.out.println("Server ready...");
//
//        Thread.sleep(5 * 60 * 1000);
//        System.out.println("Server exiting");
//        System.exit(0);
//    }
}
