//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.5-b10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.29 at 05:50:20 PM CST
//

package com.ucredit.service.web.idcard.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}message"/>
 *         &lt;element ref="{}policeCheckInfos"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "message", "policeCheckInfos" })
@XmlRootElement(name = "data")
public class Data {

    @XmlElement(required = true)
    protected Message message;
    @XmlElement(required = true)
    protected PoliceCheckInfos policeCheckInfos;

    /**
     * Gets the value of the message property.
     *
     * @return
     *         possible object is {@link Message }
     */
    public Message getMessage() {
        return this.message;
    }

    /**
     * Sets the value of the message property.
     *
     * @param value
     *        allowed object is {@link Message }
     */
    public void setMessage(Message value) {
        this.message = value;
    }

    /**
     * Gets the value of the policeCheckInfos property.
     *
     * @return
     *         possible object is {@link PoliceCheckInfos }
     */
    public PoliceCheckInfos getPoliceCheckInfos() {
        return this.policeCheckInfos;
    }

    /**
     * Sets the value of the policeCheckInfos property.
     *
     * @param value
     *        allowed object is {@link PoliceCheckInfos }
     */
    public void setPoliceCheckInfos(PoliceCheckInfos value) {
        this.policeCheckInfos = value;
    }

}
