//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.5-b10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.29 at 05:50:20 PM CST
//

package com.ucredit.service.web.idcard.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.renrendai.service.web.idcard.response package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CheckPhoto_QNAME = new QName("", "checkPhoto");
    private final static QName _IdcOriCt2_QNAME = new QName("", "idcOriCt2");
    private final static QName _Status_QNAME = new QName("", "status");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Birthday2_QNAME = new QName("", "birthday2");
    private final static QName _CompStatus_QNAME = new QName("", "compStatus");
    private final static QName _Value_QNAME = new QName("", "value");
    private final static QName _Sex2_QNAME = new QName("", "sex2");
    private final static QName _CompResult_QNAME = new QName("", "compResult");
    private final static QName _Identitycard_QNAME = new QName("",
        "identitycard");

    /**
     * Create an instance of {@link Data }
     *
     * @return
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Message }
     *
     * @return
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link PoliceCheckInfos }
     *
     * @return
     */
    public PoliceCheckInfos createPoliceCheckInfos() {
        return new PoliceCheckInfos();
    }

    /**
     * Create an instance of {@link PoliceCheckInfo }
     *
     * @return
     */
    public PoliceCheckInfo createPoliceCheckInfo() {
        return new PoliceCheckInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     * @return
     */
    @XmlElementDecl(namespace = "", name = "checkPhoto")
    public JAXBElement<String> createCheckPhoto(String value) {
        return new JAXBElement<>(ObjectFactory._CheckPhoto_QNAME, String.class,
            null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     * @return
     */
    @XmlElementDecl(namespace = "", name = "idcOriCt2")
    public JAXBElement<String> createIdcOriCt2(String value) {
        return new JAXBElement<>(ObjectFactory._IdcOriCt2_QNAME, String.class,
            null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}
     *
     * @param value
     * @return
     */
    @XmlElementDecl(namespace = "", name = "status")
    public JAXBElement<Byte> createStatus(Byte value) {
        return new JAXBElement<>(ObjectFactory._Status_QNAME, Byte.class, null,
            value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     * @return
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<>(ObjectFactory._Name_QNAME, String.class, null,
            value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     * @param value
     * @return
     */
    @XmlElementDecl(namespace = "", name = "birthday2")
    public JAXBElement<Integer> createBirthday2(Integer value) {
        return new JAXBElement<>(ObjectFactory._Birthday2_QNAME, Integer.class,
            null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}
     *
     * @param value
     * @return
     */
    @XmlElementDecl(namespace = "", name = "compStatus")
    public JAXBElement<Byte> createCompStatus(Byte value) {
        return new JAXBElement<>(ObjectFactory._CompStatus_QNAME, Byte.class,
            null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     * @return
     */
    @XmlElementDecl(namespace = "", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<>(ObjectFactory._Value_QNAME, String.class,
            null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     * @return
     */
    @XmlElementDecl(namespace = "", name = "sex2")
    public JAXBElement<String> createSex2(String value) {
        return new JAXBElement<>(ObjectFactory._Sex2_QNAME, String.class, null,
            value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     * @return
     */
    @XmlElementDecl(namespace = "", name = "compResult")
    public JAXBElement<String> createCompResult(String value) {
        return new JAXBElement<>(ObjectFactory._CompResult_QNAME, String.class,
            null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     * @return
     */
    @XmlElementDecl(namespace = "", name = "identitycard")
    public JAXBElement<String> createIdentitycard(String value) {
        return new JAXBElement<>(ObjectFactory._Identitycard_QNAME,
            String.class, null, value);
    }

}
