//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.5-b10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.29 at 05:50:20 PM CST
//

package com.ucredit.service.web.idcard.response;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}message"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}identitycard" maxOccurs="unbounded"/>
 *         &lt;element ref="{}compStatus"/>
 *         &lt;element ref="{}compResult"/>
 *         &lt;element ref="{}checkPhoto"/>
 *         &lt;element ref="{}idcOriCt2"/>
 *         &lt;element ref="{}birthday2"/>
 *         &lt;element ref="{}sex2"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "",
        propOrder = { "message", "name", "identitycard", "compStatus",
            "compResult", "checkPhoto", "idcOriCt2", "birthday2", "sex2" })
@XmlRootElement(name = "policeCheckInfo")
public class PoliceCheckInfo {

    @XmlElement(required = true)
    protected Message message;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected List<String> identitycard;
    protected String compStatus;
    @XmlElement(required = true)
    protected String compResult;
    @XmlElement(required = true)
    protected String checkPhoto;
    @XmlElement(required = true)
    protected String idcOriCt2;
    protected String birthday2;
    @XmlElement(required = true)
    protected String sex2;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the message property.
     *
     * @return
     *         possible object is {@link Message }
     */
    public Message getMessage() {
        return this.message;
    }

    /**
     * Sets the value of the message property.
     *
     * @param value
     *        allowed object is {@link Message }
     */
    public void setMessage(Message value) {
        this.message = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *         possible object is {@link String }
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *        allowed object is {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the identitycard property.
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the identitycard property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getIdentitycard().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     *
     * @return
     */
    public List<String> getIdentitycard() {
        if (this.identitycard == null) {
            this.identitycard = new ArrayList<>();
        }
        return this.identitycard;
    }

    /**
     * Gets the value of the compStatus property.
     *
     * @return
     */
    public String getCompStatus() {
        return this.compStatus;
    }

    /**
     * Sets the value of the compStatus property.
     *
     * @param value
     */
    public void setCompStatus(String value) {
        this.compStatus = value;
    }

    /**
     * Gets the value of the compResult property.
     *
     * @return
     *         possible object is {@link String }
     */
    public String getCompResult() {
        return this.compResult;
    }

    /**
     * Sets the value of the compResult property.
     *
     * @param value
     *        allowed object is {@link String }
     */
    public void setCompResult(String value) {
        this.compResult = value;
    }

    /**
     * Gets the value of the checkPhoto property.
     *
     * @return
     */
    public String getCheckPhoto() {
        return this.checkPhoto;
    }

    /**
     * Sets the value of the checkPhoto property.
     *
     * @param value
     */
    public void setCheckPhoto(String value) {
        this.checkPhoto = value;
    }

    /**
     * Gets the value of the idcOriCt2 property.
     *
     * @return
     *         possible object is {@link String }
     */
    public String getIdcOriCt2() {
        return this.idcOriCt2;
    }

    /**
     * Sets the value of the idcOriCt2 property.
     *
     * @param value
     *        allowed object is {@link String }
     */
    public void setIdcOriCt2(String value) {
        this.idcOriCt2 = value;
    }

    /**
     * Gets the value of the birthday2 property.
     *
     * @return
     */
    public String getBirthday2() {
        return this.birthday2;
    }

    /**
     * Sets the value of the birthday2 property.
     *
     * @param value
     */
    public void setBirthday2(String value) {
        this.birthday2 = value;
    }

    /**
     * Gets the value of the sex2 property.
     *
     * @return
     *         possible object is {@link String }
     */
    public String getSex2() {
        return this.sex2;
    }

    /**
     * Sets the value of the sex2 property.
     *
     * @param value
     *        allowed object is {@link String }
     */
    public void setSex2(String value) {
        this.sex2 = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *         possible object is {@link String }
     */
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *        allowed object is {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

}
