//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.5-b10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.29 at 05:50:20 PM CST
//

package com.ucredit.service.web.idcard.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}policeCheckInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "policeCheckInfo" })
@XmlRootElement(name = "policeCheckInfos")
public class PoliceCheckInfos {

    @XmlElement(required = true)
    protected PoliceCheckInfo policeCheckInfo;

    /**
     * Gets the value of the policeCheckInfo property.
     *
     * @return
     *         possible object is {@link PoliceCheckInfo }
     */
    public PoliceCheckInfo getPoliceCheckInfo() {
        return this.policeCheckInfo;
    }

    /**
     * Sets the value of the policeCheckInfo property.
     *
     * @param value
     *        allowed object is {@link PoliceCheckInfo }
     */
    public void setPoliceCheckInfo(PoliceCheckInfo value) {
        this.policeCheckInfo = value;
    }

}
